{% set name = "MPAS-Analysis" %}
{% set version = "1.11.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://github.com/MPAS-Dev/{{ name }}/archive/{{ version }}.tar.gz
  sha256: 85023957f10a2669776aaaac3d78e2540fb2f2c3b824a53cbcf9130197c7deeb

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  noarch: python
  entry_points:
    - mpas_analysis = mpas_analysis.__main__:main
    - download_analysis_data = mpas_analysis.download_data:download_analysis_data

requirements:
  host:
    - python >=3.8,<3.12
    - pip
  run:
    - python >=3.8,<3.12
    - bottleneck
    - cartopy >=0.18.0
    - cartopy_offlinedata
    - cmocean
    - dask
    - esmf >=8.4.2,<8.7.0
    - f90nml
    - geometric_features >=1.2.0
    - gsw
    - lxml
    - mache >=1.11.0
    - matplotlib-base >=3.6.0,!=3.7.2
    - mpas_tools >=0.30.0
    - nco >=4.8.1
    - netcdf4
    - numpy
    - pandas
    - pillow >=10.0.0,<11.0.0
    - progressbar2
    - pyproj
    - pyremap >=1.2.0,<2.0.0
    - python-dateutil
    - requests
    - scipy >=1.7.0
    - setuptools
    - shapely >=2.0,<3.0
    - xarray >=0.14.1

test:
  requires:
    - pytest
    - pip
  imports:
    - mpas_analysis
    - pytest
  commands:
    - pip check
    - pytest --pyargs mpas_analysis
    - mpas_analysis --help
    - download_analysis_data --help

about:
  home: https://github.com/MPAS-Dev/MPAS-Analysis
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Analysis of MPAS-Ocean and MPAS-Seaice simulations results
  description: |
    Analysis for simulations produced with Model for Prediction Across Scales
    (MPAS) components and the Energy Exascale Earth System Model (E3SM), which
    used those components.
  doc_url: https://mpas-dev.github.io/MPAS-Analysis/stable/
  dev_url: https://github.com/MPAS-Dev/MPAS-Analysis

extra:
  recipe-maintainers:
    - altheaden
    - xylar
    - jhkennedy
