{% set name = "MPAS-Analysis" %}
{% set version = "1.13.0rc3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://github.com/MPAS-Dev/{{ name }}/archive/{{ version }}.tar.gz
  sha256: 4b8544e66d09cf278e9ad1c59e39efd7ddacc50ffba25bb6d2ac3e20e221d472

build:
  number: 0
  script: {{ PYTHON }} -m pip install --no-deps --no-build-isolation -vv .
  noarch: python

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - cartopy >=0.18.0
    - cartopy_offlinedata
    - cmocean
    - dask
    - esmf >=8.4.2,<8.7.0
    - f90nml
    - geometric_features >=1.6.1
    - gsw
    - lxml
    - mache >=1.11.0
    - matplotlib-base >=3.9.0
    - mpas_tools >=0.34.0
    - nco >=4.8.1,!=5.2.6
    - netcdf4
    - numpy >=2.0,<3.0
    - pandas
    - pillow >=10.0.0,<11.0.0
    - progressbar2
    - pyproj
    - pyremap >=1.2.0,<2.0.0
    - python-dateutil
    - requests
    - scipy >=1.7.0
    - setuptools
    - shapely >=2.0,<3.0
    - xarray >=0.14.1

test:
  requires:
    - python {{ python_min }}
    - pytest
    - pip
  imports:
    - mpas_analysis
    - pytest
  commands:
    - pip check
    - pytest --pyargs mpas_analysis
    - mpas_analysis --help
    - download_analysis_data --help

about:
  home: https://github.com/MPAS-Dev/MPAS-Analysis
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Analysis of MPAS-Ocean and MPAS-Seaice simulations results
  description: |
    Analysis for simulations produced with Model for Prediction Across Scales
    (MPAS) components and the Energy Exascale Earth System Model (E3SM), which
    used those components.
  doc_url: https://mpas-dev.github.io/MPAS-Analysis/stable/
  dev_url: https://github.com/MPAS-Dev/MPAS-Analysis

extra:
  recipe-maintainers:
    - xylar
    - jhkennedy
